"""
Session manager — state machine for ENTRY / EXIT / REENTRY events.

Maintains per-visitor session state across frames.  When a visitor is first
seen the manager emits an ENTRY event.  When they disappear for longer than
EXIT_TIMEOUT_FRAMES it emits EXIT.  If the same visitor_id (matched via
Re-ID) reappears after an EXIT, it emits REENTRY.

State graph
-----------
    ABSENT ──ENTRY──► ACTIVE ──EXIT──► EXITED
                                          │
                         REENTRY ◄────────┘
                            │
                            ▼
                          ACTIVE
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)

# Frames a visitor must be absent before we emit EXIT (10 s @ 15 FPS)
EXIT_TIMEOUT_FRAMES = 150
# Minimum frames between EXIT and a new sighting to call it REENTRY
# (avoids declaring REENTRY for brief occlusion)
REENTRY_MIN_GAP_FRAMES = 45   # 3 s @ 15 FPS


class VisitorState(Enum):
    ABSENT = auto()
    ACTIVE = auto()
    EXITED = auto()


@dataclass
class SessionEvent:
    """An event generated by the session manager."""

    event_type: str              # ENTRY | EXIT | REENTRY
    visitor_id: str
    is_staff: bool = False
    frame_idx: int = 0


@dataclass
class _VisitorRecord:
    state: VisitorState = VisitorState.ABSENT
    entry_frame: int = 0
    last_seen_frame: int = 0
    exit_frame: Optional[int] = None
    is_staff: bool = False
    session_count: int = 0   # how many times this visitor entered


class SessionManager:
    """
    Manages visitor session lifecycle and generates ENTRY / EXIT / REENTRY events.

    Usage
    -----
    mgr = SessionManager(frame_rate=15)
    events = mgr.update(active_visitor_ids, is_staff_map, frame_idx)
    """

    def __init__(
        self,
        frame_rate: int = 15,
        exit_timeout_frames: int = EXIT_TIMEOUT_FRAMES,
        reentry_min_gap_frames: int = REENTRY_MIN_GAP_FRAMES,
    ) -> None:
        self.frame_rate = frame_rate
        self.exit_timeout = exit_timeout_frames
        self.reentry_min_gap = reentry_min_gap_frames
        self._records: Dict[str, _VisitorRecord] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def update(
        self,
        active_visitor_ids: List[str],
        is_staff_map: Dict[str, bool],   # visitor_id → is_staff
        frame_idx: int,
    ) -> List[SessionEvent]:
        """
        Process the current set of visible visitor_ids and return any
        ENTRY / EXIT / REENTRY events.

        Parameters
        ----------
        active_visitor_ids : visitor_ids visible in this frame.
        is_staff_map       : is_staff classification per visitor_id.
        frame_idx          : current frame index.
        """
        events: List[SessionEvent] = []
        active_set = set(active_visitor_ids)

        # --- Process newly visible visitors ---
        for visitor_id in active_set:
            is_staff = is_staff_map.get(visitor_id, False)
            record = self._records.get(visitor_id)

            if record is None:
                # First time we see this visitor → ENTRY
                record = _VisitorRecord(
                    state=VisitorState.ACTIVE,
                    entry_frame=frame_idx,
                    last_seen_frame=frame_idx,
                    is_staff=is_staff,
                    session_count=1,
                )
                self._records[visitor_id] = record
                events.append(
                    SessionEvent(
                        event_type="ENTRY",
                        visitor_id=visitor_id,
                        is_staff=is_staff,
                        frame_idx=frame_idx,
                    )
                )
                logger.debug("ENTRY  visitor=%s frame=%d", visitor_id, frame_idx)

            elif record.state == VisitorState.EXITED:
                # Reappeared after exit → REENTRY (if gap is large enough)
                gap = frame_idx - (record.exit_frame or frame_idx)
                if gap >= self.reentry_min_gap:
                    record.state = VisitorState.ACTIVE
                    record.entry_frame = frame_idx
                    record.last_seen_frame = frame_idx
                    record.is_staff = is_staff
                    record.session_count += 1
                    events.append(
                        SessionEvent(
                            event_type="REENTRY",
                            visitor_id=visitor_id,
                            is_staff=is_staff,
                            frame_idx=frame_idx,
                        )
                    )
                    logger.debug(
                        "REENTRY visitor=%s frame=%d gap=%d", visitor_id, frame_idx, gap
                    )
                else:
                    # Too short — treat as same session continuation
                    record.state = VisitorState.ACTIVE
                    record.last_seen_frame = frame_idx

            else:
                # Already ACTIVE — just update last seen
                record.last_seen_frame = frame_idx
                record.is_staff = is_staff

        # --- Check for visitors who have been absent too long → EXIT ---
        for visitor_id, record in self._records.items():
            if visitor_id in active_set:
                continue
            if record.state != VisitorState.ACTIVE:
                continue
            absent_frames = frame_idx - record.last_seen_frame
            if absent_frames >= self.exit_timeout:
                record.state = VisitorState.EXITED
                record.exit_frame = record.last_seen_frame  # use last sighting as exit
                events.append(
                    SessionEvent(
                        event_type="EXIT",
                        visitor_id=visitor_id,
                        is_staff=record.is_staff,
                        frame_idx=record.last_seen_frame,
                    )
                )
                logger.debug(
                    "EXIT   visitor=%s frame=%d dwell_frames=%d",
                    visitor_id,
                    record.last_seen_frame,
                    record.last_seen_frame - record.entry_frame,
                )

        return events

    def get_dwell_ms(self, visitor_id: str, current_frame: int) -> int:
        """Return total dwell time in milliseconds for an active visitor."""
        record = self._records.get(visitor_id)
        if record is None:
            return 0
        frames = current_frame - record.entry_frame
        return int(frames / self.frame_rate * 1000)

    def is_active(self, visitor_id: str) -> bool:
        """Return True if the visitor is currently inside the store."""
        record = self._records.get(visitor_id)
        return record is not None and record.state == VisitorState.ACTIVE

    def reset(self) -> None:
        """Clear all session state (between video files)."""
        self._records.clear()

    def summary(self) -> dict:
        """Return summary statistics for monitoring."""
        total = len(self._records)
        active = sum(
            1 for r in self._records.values() if r.state == VisitorState.ACTIVE
        )
        exited = sum(
            1 for r in self._records.values() if r.state == VisitorState.EXITED
        )
        reentries = sum(
            1 for r in self._records.values() if r.session_count > 1
        )
        return {
            "total_unique_visitors": total,
            "currently_active": active,
            "exited": exited,
            "reentries": reentries,
        }
