"""
Zone engine — maps person track foot-points to store zones and emits
zone-level events (ZONE_ENTER, ZONE_DWELL, ZONE_EXIT) as well as
billing-queue events (BILLING_QUEUE_JOIN, BILLING_QUEUE_ABANDON).

Zone definitions are loaded from store_layout.json which contains
polygon coordinates in normalised floor-plan space (0–100 or 0–300 etc.)
mapped to pixel space via a homography transform or direct scale factor.

For simplicity in this implementation we use a scale-factor approach:
the floor plan dimensions are treated as pixel coordinates divided by a
known camera resolution scale.  If a proper homography matrix is provided
per camera in store_layout.json it will be used instead.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

import numpy as np

logger = logging.getLogger(__name__)

# How often (in frames) to emit a ZONE_DWELL event while a person is stationary
DWELL_EMIT_INTERVAL_FRAMES = 75   # every 5 seconds @ 15 FPS


@dataclass
class ZoneDefinition:
    """A named polygon zone from the store layout."""

    zone_id: str
    label: str
    zone_type: str                    # 'entrance', 'shopping', 'billing'
    polygon: np.ndarray               # shape (N, 2) float32, floor-plan coords


@dataclass
class ZoneEvent:
    """An event generated by the zone engine."""

    event_type: str                   # ZONE_ENTER | ZONE_DWELL | ZONE_EXIT
    visitor_id: str
    zone_id: str
    dwell_ms: Optional[int] = None
    is_billing_queue: bool = False
    extra_event_type: Optional[str] = None  # BILLING_QUEUE_JOIN / BILLING_QUEUE_ABANDON


class ZoneEngine:
    """
    Checks each tracked person's foot-point against zone polygons and
    generates zone events.

    Usage
    -----
    engine = ZoneEngine(zones, frame_rate=15, scale_x=1.0, scale_y=1.0)
    events = engine.update(tracks, frame_idx, visitor_map)
    """

    def __init__(
        self,
        zones: List[ZoneDefinition],
        frame_rate: int = 15,
        # Scale factors to convert floor-plan polygon units → pixel space
        scale_x: float = 1.0,
        scale_y: float = 1.0,
    ) -> None:
        self.zones = zones
        self.frame_rate = frame_rate
        self.scale_x = scale_x
        self.scale_y = scale_y

        # visitor_id → set of zone_ids currently occupied
        self._current_zones: Dict[str, Set[str]] = {}
        # visitor_id → {zone_id: entry_frame}
        self._zone_entry_frame: Dict[str, Dict[str, int]] = {}
        # visitor_id → {zone_id: last_dwell_emit_frame}
        self._last_dwell_emit: Dict[str, Dict[str, int]] = {}
        # Current set of visitor_ids in billing zone
        self._billing_occupants: Set[str] = set()

        # NOTE: Zone polygons are kept in their original layout coordinate space.
        # Foot-points (pixel space) are divided by scale_x/scale_y in update()
        # to convert them into layout space before the point-in-polygon test.

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def update(
        self,
        tracks: list,
        frame_idx: int,
        visitor_map: Dict[int, str],    # track_id → visitor_id
        is_staff_map: Dict[int, bool],  # track_id → is_staff
    ) -> List[ZoneEvent]:
        """
        Process all active tracks and return any new zone events.

        Parameters
        ----------
        tracks       : List[Track] from PersonTracker.update().
        frame_idx    : Current frame index.
        visitor_map  : Mapping from track_id → visitor_id (from ReIDModule).
        is_staff_map : Mapping from track_id → is_staff flag.
        """
        events: List[ZoneEvent] = []

        active_visitors: Set[str] = set()

        for track in tracks:
            visitor_id = visitor_map.get(track.track_id)
            if visitor_id is None:
                continue

            active_visitors.add(visitor_id)
            px, py = track.foot_point   # pixel coords from bounding box

            # Convert foot-point from pixel space → layout space.
            # scale_x = max_layout_x / frame_width  (e.g. 100/1920 = 0.052)
            # Dividing pixel coords by (1/scale_x) == multiplying by scale_x
            # brings them into the same 0..100 / 0..300 coordinate space as
            # the zone polygons defined in store_layout.json.
            foot = (px * self.scale_x, py * self.scale_y)

            # Determine which zones this foot-point is inside
            current_zones_for_visitor = self._current_zones.setdefault(
                visitor_id, set()
            )
            new_zones: Set[str] = set()

            for zone in self.zones:
                if _point_in_polygon(foot, zone.polygon):
                    new_zones.add(zone.zone_id)

            # --- Zone ENTER events ---
            entered = new_zones - current_zones_for_visitor
            for zone_id in entered:
                zone_def = self._zone_by_id(zone_id)
                self._zone_entry_frame.setdefault(visitor_id, {})[zone_id] = frame_idx
                self._last_dwell_emit.setdefault(visitor_id, {})[zone_id] = frame_idx
                ev = ZoneEvent(
                    event_type="ZONE_ENTER",
                    visitor_id=visitor_id,
                    zone_id=zone_id,
                )
                # Billing queue join
                if zone_def and zone_def.zone_type == "billing":
                    ev.is_billing_queue = True
                    ev.extra_event_type = "BILLING_QUEUE_JOIN"
                    self._billing_occupants.add(visitor_id)
                events.append(ev)

            # --- Zone DWELL events (periodic) ---
            for zone_id in new_zones:
                entry_frame = self._zone_entry_frame.get(visitor_id, {}).get(zone_id, frame_idx)
                last_emit = self._last_dwell_emit.get(visitor_id, {}).get(zone_id, frame_idx)
                if frame_idx - last_emit >= DWELL_EMIT_INTERVAL_FRAMES:
                    dwell_ms = int(
                        (frame_idx - entry_frame) / self.frame_rate * 1000
                    )
                    events.append(
                        ZoneEvent(
                            event_type="ZONE_DWELL",
                            visitor_id=visitor_id,
                            zone_id=zone_id,
                            dwell_ms=dwell_ms,
                        )
                    )
                    self._last_dwell_emit[visitor_id][zone_id] = frame_idx

            # --- Zone EXIT events ---
            exited = current_zones_for_visitor - new_zones
            for zone_id in exited:
                zone_def = self._zone_by_id(zone_id)
                entry_frame = self._zone_entry_frame.get(visitor_id, {}).get(
                    zone_id, frame_idx
                )
                dwell_ms = int(
                    (frame_idx - entry_frame) / self.frame_rate * 1000
                )
                ev = ZoneEvent(
                    event_type="ZONE_EXIT",
                    visitor_id=visitor_id,
                    zone_id=zone_id,
                    dwell_ms=dwell_ms,
                )
                # Billing queue abandon (left billing zone before purchase confirmation)
                if zone_def and zone_def.zone_type == "billing":
                    if visitor_id in self._billing_occupants:
                        ev.extra_event_type = "BILLING_QUEUE_ABANDON"
                        self._billing_occupants.discard(visitor_id)
                events.append(ev)
                # Clear zone entry tracking
                self._zone_entry_frame.get(visitor_id, {}).pop(zone_id, None)

            # Update current zones
            self._current_zones[visitor_id] = new_zones

        # --- Handle visitors who disappeared from frame ---
        disappeared = set(self._current_zones.keys()) - active_visitors
        for visitor_id in disappeared:
            for zone_id in list(self._current_zones.get(visitor_id, set())):
                zone_def = self._zone_by_id(zone_id)
                entry_frame = self._zone_entry_frame.get(visitor_id, {}).get(
                    zone_id, frame_idx
                )
                dwell_ms = int(
                    (frame_idx - entry_frame) / self.frame_rate * 1000
                )
                ev = ZoneEvent(
                    event_type="ZONE_EXIT",
                    visitor_id=visitor_id,
                    zone_id=zone_id,
                    dwell_ms=dwell_ms,
                )
                if zone_def and zone_def.zone_type == "billing":
                    if visitor_id in self._billing_occupants:
                        ev.extra_event_type = "BILLING_QUEUE_ABANDON"
                        self._billing_occupants.discard(visitor_id)
                events.append(ev)
            self._current_zones.pop(visitor_id, None)
            self._zone_entry_frame.pop(visitor_id, None)
            self._last_dwell_emit.pop(visitor_id, None)

        return events

    def get_queue_depth(self) -> int:
        """Return current number of visitors in the billing zone."""
        return len(self._billing_occupants)

    def reset(self) -> None:
        """Clear all state."""
        self._current_zones.clear()
        self._zone_entry_frame.clear()
        self._last_dwell_emit.clear()
        self._billing_occupants.clear()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _zone_by_id(self, zone_id: str) -> Optional[ZoneDefinition]:
        for z in self.zones:
            if z.zone_id == zone_id:
                return z
        return None


# ── Factory ────────────────────────────────────────────────────────────────────

def load_zones_from_layout(store_layout: dict, store_id: str) -> List[ZoneDefinition]:
    """
    Parse store_layout.json and return ZoneDefinition list for the given store.

    Parameters
    ----------
    store_layout : dict  — parsed JSON from data/store_layout.json
    store_id     : str   — e.g. 'store_001'
    """
    store = store_layout.get("stores", {}).get(store_id, {})
    zones_raw = store.get("zones", {})

    zones: List[ZoneDefinition] = []
    for zone_id, zone_data in zones_raw.items():
        polygon = np.array(zone_data["polygon"], dtype=np.float32)
        zones.append(
            ZoneDefinition(
                zone_id=zone_id,
                label=zone_data.get("label", zone_id),
                zone_type=zone_data.get("type", "shopping"),
                polygon=polygon,
            )
        )

    logger.info(
        "Loaded %d zones for store %s: %s",
        len(zones),
        store_id,
        [z.zone_id for z in zones],
    )
    return zones


# ── Geometry ───────────────────────────────────────────────────────────────────

def _point_in_polygon(
    point: Tuple[float, float], polygon: np.ndarray
) -> bool:
    """
    Ray-casting point-in-polygon test.

    Parameters
    ----------
    point   : (x, y) tuple in the same coordinate space as polygon.
    polygon : (N, 2) array of [x, y] vertices.
    """
    x, y = point
    n = len(polygon)
    inside = False
    j = n - 1
    for i in range(n):
        xi, yi = polygon[i]
        xj, yj = polygon[j]
        if ((yi > y) != (yj > y)) and (
            x < (xj - xi) * (y - yi) / (yj - yi + 1e-9) + xi
        ):
            inside = not inside
        j = i
    return inside
